import cv2
from ultralytics import YOLO
from flask import Flask, Response
from picamera2 import Picamera2
import os

# --- 1. CONFIG ---
# This path should point to the best.pt generated by train_yolo_classifier.py
MODEL_PATH = '/home/azure/panel-defect/best.pt'
app = Flask(__name__)

# --- 2. LOAD YOLO CLASSIFIER MODEL ---
print("Loading YOLO Classifier AI Model...")
model = YOLO(MODEL_PATH)

# --- 3. INITIALIZE NATIVE CAMERA ---
print("Waking up hardware camera...")
picam2 = Picamera2()
# Configure capture resolution
config = picam2.create_preview_configuration(main={"size": (640, 480)})
picam2.configure(config)
picam2.start()

# --- 4. VIDEO GENERATOR (ESP32 IMAGE-BIT COMPRESSION) ---
def generate_frames():
    while True:
        # 1. Grab frame from the ribbon cable and fix color channel ordering
        frame = picam2.capture_array()
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)

        # 2. Run YOLO Classification Inference
        results = model.predict(frame, conf=0.25, verbose=False)

        # 3. Extract predictions for custom HUD overlay if available
        annotated_frame = frame.copy()
        if hasattr(results[0], 'probs') and results[0].probs is not None:
            top_class_idx = results[0].probs.top1
            top_conf = results[0].probs.top1conf.item()
            label = results[0].names[top_class_idx]

            # Filter out healthy classes to avoid ground-station noise
            if label not in ["Clean", "Good"] and top_conf > 0.85:
                # Draw a prominent alert bar across the top of the image bit
                cv2.rectangle(annotated_frame, (0, 0), (640, 40), (0, 0, 204), -1)
                cv2.putText(annotated_frame, f"ALERT: {label} ({top_conf*100:.1f}%)", (15, 26),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)
            else:
                # Normal operational status HUD
                cv2.rectangle(annotated_frame, (0, 0), (640, 40), (0, 153, 76), -1)
                cv2.putText(annotated_frame, f"SYSTEM STATUS: {label.upper()}", (15, 26),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
        else:
            # Fallback to Ultralytics native plotter if structural parsing alters
            annotated_frame = results[0].plot()

        # 4. THE ESP32 TRICK: Compress the frame quality aggressively into a tight "image bit"
        # This dramatically shrinks frame sizes down to ~20KB, allowing smooth multi-fps streaming
        encode_param = [int(cv2.IMWRITE_JPEG_QUALITY), 50]
        ret, buffer = cv2.imencode('.jpg', annotated_frame, encode_param)
        frame_bytes = buffer.tobytes()

        # 5. Fast-pipe the payload chunks to the HTTP boundary socket
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_bytes + b'\r\n')

# --- 5. WEB ROUTES ---
@app.route('/')
def index():
    return """
    <html>
        <head>
            <title>Solar Drone Core</title>
        </head>
        <body style="text-align: center; font-family: Arial, sans-serif; background-color: #1e1e1e; color: white; margin-top: 20px;">
            <h2>Solar Drone - YOLO Image-Bit Analytics Stream</h2>
            <div style="margin: 20px auto; max-width: 640px;">
                <img src="/video_feed" style="border: 4px solid #333; border-radius: 8px; box-shadow: 0px 4px 15px rgba(0,0,0,0.5);" width="640" height="480">
            </div>
            <br>
            <form action="/shutdown" method="POST">
                <button style="background-color: #cc0000; color: white; padding: 15px 40px; font-size: 18px; font-weight: bold; border: none; border-radius: 5px; cursor: pointer; transition: 0.2s; box-shadow: 0 4px 6px rgba(0,0,0,0.3);">
                    POWER OFF DRONE OS
                </button>
            </form>
            <p style="color: #888; font-size: 13px; margin-top: 15px;">⚠️ Verify drone is completely stationary and landed before triggering OS shutdown.</p>
        </body>
    </html>
    """

@app.route('/video_feed')
def video_feed():
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')


if __name__ == "__main__":
    print("AI Stream Processing Active. Network binding initialized on port 5000.")
    app.run(host='0.0.0.0', port=5000, debug=False, threaded=True)